#!/usr/bin/python3
import sys
import math

def find_factors (num):
    for i in range(2, num):
        if num % i == 0:
            return i, num // i

if __name__ == "__main__":
    filename = sys.argv[1]
    with open(filename, "r") as file:
        for line in file:
            num = int(line.strip())
            q, p = find_factors(num)
            print(f"{num}={q}*{p}")
